### ISSUE TITLE
Documentation doesn't say the magic version of linux needed to install

### ISSUE THREAD

**Issue by garlandcrow** [phasebook/phasebook#30]
I've tried 6 different of the most popular linux distros and serveral different version new and old of them and none can make it past your installation steps for various things not having the correct version or library not being installed. So would very much like if you could reveal to us plebs what the magic version is you were running on when you wrote this, then maybe someone could actually install and try out the tool.

**Comment by HaploKit** [comment]
Sorry for this. But we were able to install and run it on several linux systems, such as:
`cat /proc/version`

Linux version 5.4.0-73-generic (buildd@lcy01-amd64-019) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021

Linux version 5.4.17-100.fc30.x86_64 (mockbuild@bkernel03.phx2.fedoraproject.org) (gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)) #1 SMP Sat Feb 1 19:15:35 UTC 2020

Linux version 3.10.0-1160.36.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Jul 21 11:57:15 UTC 2021
